# Be careful there is no whitespace after

profiles=~~/script-opts/track-selector-profiles.json
languages=~~/script-opts/track-selector-languages.json
exceptions=~~/script-opts/track-selector-exceptions.json

# Check title since not all tracks are flagged correctly
# Forced: "forced", "sign"
# Hearing-impaired: "sdh", "[cc]", "(cc)"
# Visual-impaired: "descrip" 
forced_title_check=yes
hearing_impaired_title_check=yes
visual_impaired_title_check=yes

# If multiple tracks match, precedence decides which is chosen
# Audio: codec, channels, title, default, bitrate, id
# Subtitle: codec, title, default, bitrate, id
# bitrate = Highest chosen
# id = Lowest chosen
# default = Has default flag
audio_precedence=codec,channels,title,default,bitrate,id
subtitle_precedence=codec,title,default,id

# Precidence
audio_codec_order=pcm,dts-hd,truehd,flac,dts,opus,eac3,ac3,aac,vorbis,mp3,mp2
subtitle_codec_order=ass,subrip,mov_text,webvtt,hdmv_pgs_subtitle,dvd_subtitle
audio_channels_order=8,7,6,5,4,3,2,1
# Placeholders. Probably only useful for choosing original vs dub or sub groups
audio_title_order=original,dub
subtitle_title_order=mtbb,commie

# Toggle excepting playing files path
keybind_toggle_exception=e
# Show menu of matched profiles
keybind_show_profile_menu=p

# OSD messages on profile changes and exceptions
osd_messages=yes
osd_duration=3

# Additional output for debugging
log=no
