# Be careful there is no whitespace after

profiles=~~/script-opts/track-selector-profiles.json
languages=~~/script-opts/language-code-mapping.json
exceptions=~~/script-opts/track-selector-exceptions.json

# Check title for "forced", "sdh", "descrip" respectively since not all tracks are flagged correct
forced_check=yes
hearing_impaired_check=yes
visual_impaired_check=yes

# If multiple tracks match, precedence decides which is chosen
audio_precedence=codec
subtitle_precedence=codec
# Audio: codec, channels, bitrate, id, default
# Subtitle: codec, id, default, title
# bitrate = Highest chosen
# id = Lowest chosen
# default = Has default tag
# Audio ordered by uncompressed to lossless to lossy compressed
audio_codec_order=pcm,dts-hd,truehd,flac,dts,opus,eac3,ac3,aac,vorbis,mp3,mp2
# Subtitle ordered by the ability to restyle
subtitle_codec_order=ass,subrip,mov_text,webvtt,hdmv_pgs_subtitle,dvd_subtitle
# Advanced Substation Alpha, SRT, MP4 Time Text, WebVTT (WEB), PGS (BluRay), Vobsub (DVD)
audio_channel_order=8,7,6,5,4,3,2,1
# Placeholders. Probably only useful for sub groups
subtitle_title_order=mtbb,commie

# If no profile is matched apply these track preferences
# String = alang/slang, Number = aid/sid (Use 0 instead of "no" to disable)
audio_fallback=eng
subtitle_fallback=0

# Except playing files path
keybind_exception=e
# Show menu of matched profiles
keybind_menu=p

# Additional output
log=no